pipeline {
  agent any
  
  stages {
    stage('Checkout') {
      steps {
        checkout scm
      }
    }
    stage('Build and Run') {
      steps {
        sh '''
          echo "print('Hello, World!')" > hello.py
          python3 hello.py
        '''
      }
    }
  }
}
